### ISSUE TITLE
global name 'OpenSSL' is not defined

### ISSUE THREAD

**Issue by muppeth** [jaywink/diaspora-tools#2]
Getting errors when trying to migrate my contacts. Thought it might be an issue with my pod so I created dummy accounts on diasp.eu to test.
error:
**** Family ****
Traceback (most recent call last):
  File "diaspora-tools.py", line 203, in <module>
    main()
  File "diaspora-tools.py", line 197, in main
    counts = migrate_contacts(args)
  File "diaspora-tools.py", line 132, in migrate_contacts
    except (AttributeError, OpenSSL.SSL.ZeroReturnError), e:
NameError: global name 'OpenSSL' is not defined

**Comment by jaywink** [comment]
Did you install the [requirements](https://github.com/jaywink/diaspora-tools/blob/master/requirements/requirements.txt)?

What Python version?

**Comment by muppeth** [comment]
I had all requirements already installed except for diaspy. I'm running python2.7.10 on archlinux

**Comment by muppeth** [comment]
I've added import OpenSSL and now I'm getting:
DEBUG: error from diaspy.models.Aspect.getUsers() - retrying, ctrl-c to stop...

**Comment by jaywink** [comment]
Mmmyeah, the `OpenSSL` thingy seems to be a missing import, my fault, will push that fix, but the real problem why it is ending there is that `diaspy` is broken for pods running 0.5.x code (logged [an issue](https://github.com/marekjm/diaspy/issues/21)) - the problem is really that since diaspora doesn't have an API yet, diaspy uses the unofficial, unstable, JSON feeds that diaspora uses internally. These are not guaranteed to be stable and like now changed for aspects in 0.5.

So, unfortunally, this needs to be fixed in `diaspy` side first.

**Comment by jaywink** [comment]
Sorry, wasn't supposed to close :)

**Comment by muppeth** [comment]
Thanks for the effort. Pity that migration is broken on latest diaspora (both pods are running 0.5.1). I guess, best thing to do now is to slowly move all the contacts (all 114 of them).

Don't know if you want to keep the issue open until diaspy is patched. 
I'll be following development of diaspy in the mean time.
